package com.gielinor_sessions.resources.achievement_diary;

import com.gielinor_sessions.resources.requirements.IRequirement;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.Client;
import net.runelite.api.gameval.VarbitID;

@RequiredArgsConstructor
@Getter
public enum AD_GROUP
{
	ARDOUGNE_EASY("Ardougne Easy", VarbitID.ARDOUGNE_DIARY_EASY_COMPLETE),
	ARDOUGNE_MEDIUM("Ardougne Medium", VarbitID.ARDOUGNE_DIARY_MEDIUM_COMPLETE),
	ARDOUGNE_HARD("Ardougne Hard", VarbitID.ARDOUGNE_DIARY_HARD_COMPLETE),
	ARDOUGNE_ELITE("Ardougne Elite", VarbitID.ARDOUGNE_DIARY_ELITE_COMPLETE),

	DESERT_EASY("Desert Easy", VarbitID.DESERT_DIARY_EASY_COMPLETE),
	DESERT_MEDIUM("Desert Medium", VarbitID.DESERT_DIARY_MEDIUM_COMPLETE),
	DESERT_HARD("Desert Hard", VarbitID.DESERT_DIARY_HARD_COMPLETE),
	DESERT_ELITE("Desert Elite", VarbitID.DESERT_DIARY_ELITE_COMPLETE),

	FALADOR_EASY("Falador Easy", VarbitID.FALADOR_DIARY_EASY_COMPLETE),
	FALADOR_MEDIUM("Falador Medium", VarbitID.FALADOR_DIARY_MEDIUM_COMPLETE),
	FALADOR_HARD("Falador Hard", VarbitID.FALADOR_DIARY_HARD_COMPLETE),
	FALADOR_ELITE("Falador Elite", VarbitID.FALADOR_DIARY_ELITE_COMPLETE),

	FREMENNIK_EASY("Fremennik Easy", VarbitID.FREMENNIK_DIARY_EASY_COMPLETE),
	FREMENNIK_MEDIUM("Fremennik Medium", VarbitID.FREMENNIK_DIARY_MEDIUM_COMPLETE),
	FREMENNIK_HARD("Fremennik Hard", VarbitID.FREMENNIK_DIARY_HARD_COMPLETE),
	FREMENNIK_ELITE("Fremennik Elite", VarbitID.FREMENNIK_DIARY_ELITE_COMPLETE),

	KANDARIN_EASY("Kandarin Easy", VarbitID.KANDARIN_DIARY_EASY_COMPLETE),
	KANDARIN_MEDIUM("Kandarin Medium", VarbitID.KANDARIN_DIARY_MEDIUM_COMPLETE),
	KANDARIN_HARD("Kandarin Hard", VarbitID.KANDARIN_DIARY_HARD_COMPLETE),
	KANDARIN_ELITE("Kandarin Elite", VarbitID.KANDARIN_DIARY_ELITE_COMPLETE),

	KARAMJA_EASY("Karamja Easy", VarbitID.ATJUN_EASY_DONE),
	KARAMJA_MEDIUM("Karamja Medium", VarbitID.ATJUN_MED_DONE),
	KARAMJA_HARD("Karamja Hard", VarbitID.ATJUN_HARD_DONE),
	KARAMJA_ELITE("Karamja Elite", VarbitID.KARAMJA_DIARY_ELITE_COMPLETE),

	KOUREND_KEBOS_EASY("Kourend & Kebos Easy", VarbitID.KOUREND_DIARY_EASY_COMPLETE),
	KOUREND_KEBOS_MEDIUM("Kourend & Kebos Medium", VarbitID.KOUREND_DIARY_MEDIUM_COMPLETE),
	KOUREND_KEBOS_HARD("Kourend & Kebos Hard", VarbitID.KOUREND_DIARY_HARD_COMPLETE),
	KOUREND_KEBOS_ELITE("Kourend & Kebos Elite", VarbitID.KOUREND_DIARY_ELITE_COMPLETE),

	LUMBRIDGE_DRAYNOR_EASY("Lumbridge & Draynor Easy", VarbitID.LUMBRIDGE_DIARY_EASY_COMPLETE),
	LUMBRIDGE_DRAYNOR_MEDIUM("Lumbridge & Draynor Medium", VarbitID.LUMBRIDGE_DIARY_MEDIUM_COMPLETE),
	LUMBRIDGE_DRAYNOR_HARD("Lumbridge & Draynor Hard", VarbitID.LUMBRIDGE_DIARY_HARD_COMPLETE),
	LUMBRIDGE_DRAYNOR_ELITE("Lumbridge & Draynor Elite", VarbitID.LUMBRIDGE_DIARY_ELITE_COMPLETE),

	MORYTANIA_EASY("Morytania Easy", VarbitID.MORYTANIA_DIARY_EASY_COMPLETE),
	MORYTANIA_MEDIUM("Morytania Medium", VarbitID.MORYTANIA_DIARY_MEDIUM_COMPLETE),
	MORYTANIA_HARD("Morytania Hard", VarbitID.MORYTANIA_DIARY_HARD_COMPLETE),
	MORYTANIA_ELITE("Morytania Elite", VarbitID.MORYTANIA_DIARY_ELITE_COMPLETE),

	VARROCK_EASY("Varrock Easy", VarbitID.VARROCK_DIARY_EASY_COMPLETE),
	VARROCK_MEDIUM("Varrock Medium", VarbitID.VARROCK_DIARY_MEDIUM_COMPLETE),
	VARROCK_HARD("Varrock Hard", VarbitID.VARROCK_DIARY_HARD_COMPLETE),
	VARROCK_ELITE("Varrock Elite", VarbitID.VARROCK_DIARY_ELITE_COMPLETE),

	WESTERN_PROVINCES_EASY("Western Provinces Easy", VarbitID.WESTERN_DIARY_EASY_COMPLETE),
	WESTERN_PROVINCES_MEDIUM("Western Provinces Medium", VarbitID.WESTERN_DIARY_MEDIUM_COMPLETE),
	WESTERN_PROVINCES_HARD("Western Provinces Hard", VarbitID.WESTERN_DIARY_HARD_COMPLETE),
	WESTERN_PROVINCES_ELITE("Western Provinces Elite", VarbitID.WESTERN_DIARY_ELITE_COMPLETE),

	WILDERNESS_EASY("Wilderness Easy", VarbitID.WILDERNESS_DIARY_EASY_COMPLETE),
	WILDERNESS_MEDIUM("Wilderness Medium", VarbitID.WILDERNESS_DIARY_MEDIUM_COMPLETE),
	WILDERNESS_HARD("Wilderness Hard", VarbitID.WILDERNESS_DIARY_HARD_COMPLETE),
	WILDERNESS_ELITE("Wilderness Elite", VarbitID.WILDERNESS_DIARY_ELITE_COMPLETE);

	private final String name;
	private final int varbitID;

	public boolean isCompleted(Client client)
	{
		return client.getVarbitValue(varbitID) == IRequirement.COMPLETED;
	}
}