package com.gielinor_sessions.resources.achievement_diary;

import com.gielinor_sessions.resources.requirements.IRequirement;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.Client;
import net.runelite.api.gameval.VarbitID;

enum AD_TIER
{
	EASY,
	MEDIUM,
	HARD,
	ELITE
}

@RequiredArgsConstructor
@Getter
public enum AD_GROUP
{
	ARDOUGNE_EASY("Ardougne Easy", AD_TIER.EASY, VarbitID.ARDOUGNE_DIARY_EASY_COMPLETE),
	ARDOUGNE_MEDIUM("Ardougne Medium", AD_TIER.MEDIUM, VarbitID.ARDOUGNE_DIARY_MEDIUM_COMPLETE),
	ARDOUGNE_HARD("Ardougne Medium", AD_TIER.HARD, VarbitID.ARDOUGNE_DIARY_HARD_COMPLETE),
	ARDOUGNE_ELITE("Ardougne Medium", AD_TIER.ELITE, VarbitID.ARDOUGNE_DIARY_ELITE_COMPLETE),

	DESERT_EASY("Desert Easy", AD_TIER.EASY, VarbitID.DESERT_DIARY_EASY_COMPLETE),
	DESERT_MEDIUM("Desert Medium", AD_TIER.MEDIUM, VarbitID.DESERT_DIARY_MEDIUM_COMPLETE),
	DESERT_HARD("Desert Medium", AD_TIER.HARD, VarbitID.DESERT_DIARY_HARD_COMPLETE),
	DESERT_ELITE("Desert Medium", AD_TIER.ELITE, VarbitID.DESERT_DIARY_ELITE_COMPLETE),

	FALADOR_EASY("Falador Easy", AD_TIER.EASY, VarbitID.FALADOR_DIARY_EASY_COMPLETE),
	FALADOR_MEDIUM("Falador Medium", AD_TIER.MEDIUM, VarbitID.FALADOR_DIARY_MEDIUM_COMPLETE),
	FALADOR_HARD("Falador Medium", AD_TIER.HARD, VarbitID.FALADOR_DIARY_HARD_COMPLETE),
	FALADOR_ELITE("Falador Medium", AD_TIER.ELITE, VarbitID.FALADOR_DIARY_ELITE_COMPLETE),

	FREMENNIK_EASY("Fremennik Easy", AD_TIER.EASY, VarbitID.FREMENNIK_DIARY_EASY_COMPLETE),
	FREMENNIK_MEDIUM("Fremennik Medium", AD_TIER.MEDIUM, VarbitID.FREMENNIK_DIARY_MEDIUM_COMPLETE),
	FREMENNIK_HARD("Fremennik Medium", AD_TIER.HARD, VarbitID.FREMENNIK_DIARY_HARD_COMPLETE),
	FREMENNIK_ELITE("Fremennik Medium", AD_TIER.ELITE, VarbitID.FREMENNIK_DIARY_ELITE_COMPLETE),

	KANDARIN_EASY("Kandarin Easy", AD_TIER.EASY, VarbitID.KANDARIN_DIARY_EASY_COMPLETE),
	KANDARIN_MEDIUM("Kandarin Medium", AD_TIER.MEDIUM, VarbitID.KANDARIN_DIARY_MEDIUM_COMPLETE),
	KANDARIN_HARD("Kandarin Medium", AD_TIER.HARD, VarbitID.KANDARIN_DIARY_HARD_COMPLETE),
	KANDARIN_ELITE("Kandarin Medium", AD_TIER.ELITE, VarbitID.KANDARIN_DIARY_ELITE_COMPLETE),

	KARAMJA_EASY("Karamja Easy", AD_TIER.EASY, VarbitID.ATJUN_EASY_DONE),
	KARAMJA_MEDIUM("Karamja Medium", AD_TIER.MEDIUM, VarbitID.ATJUN_MED_DONE),
	KARAMJA_HARD("Karamja Medium", AD_TIER.HARD, VarbitID.ATJUN_HARD_DONE),
	KARAMJA_ELITE("Karamja Medium", AD_TIER.ELITE, VarbitID.KARAMJA_DIARY_ELITE_COMPLETE),

	KOUREND_KEBOS_EASY("Kourend & Kebos Easy", AD_TIER.EASY, VarbitID.KOUREND_DIARY_EASY_COMPLETE),
	KOUREND_KEBOS_MEDIUM("Kourend & Kebos Medium", AD_TIER.MEDIUM, VarbitID.KOUREND_DIARY_MEDIUM_COMPLETE),
	KOUREND_KEBOS_HARD("Kourend & Kebos Medium", AD_TIER.HARD, VarbitID.KOUREND_DIARY_HARD_COMPLETE),
	KOUREND_KEBOS_ELITE("Kourend & Kebos Medium", AD_TIER.ELITE, VarbitID.KOUREND_DIARY_ELITE_COMPLETE),

	LUMBRIDGE_DRAYNOR_EASY("Lumbridge & Draynor Easy", AD_TIER.EASY, VarbitID.LUMBRIDGE_DIARY_EASY_COMPLETE),
	LUMBRIDGE_DRAYNOR_MEDIUM("Lumbridge & Draynor Medium", AD_TIER.MEDIUM, VarbitID.LUMBRIDGE_DIARY_MEDIUM_COMPLETE),
	LUMBRIDGE_DRAYNOR_HARD("Lumbridge & Draynor Medium", AD_TIER.HARD, VarbitID.LUMBRIDGE_DIARY_HARD_COMPLETE),
	LUMBRIDGE_DRAYNOR_ELITE("Lumbridge & Draynor Medium", AD_TIER.ELITE, VarbitID.LUMBRIDGE_DIARY_ELITE_COMPLETE),

	MORYTANIA_EASY("Morytania Easy", AD_TIER.EASY, VarbitID.MORYTANIA_DIARY_EASY_COMPLETE),
	MORYTANIA_MEDIUM("Morytania Medium", AD_TIER.MEDIUM, VarbitID.MORYTANIA_DIARY_MEDIUM_COMPLETE),
	MORYTANIA_HARD("Morytania Medium", AD_TIER.HARD, VarbitID.MORYTANIA_DIARY_HARD_COMPLETE),
	MORYTANIA_ELITE("Morytania Medium", AD_TIER.ELITE, VarbitID.MORYTANIA_DIARY_ELITE_COMPLETE),

	VARROCK_EASY("Varrock Easy", AD_TIER.EASY, VarbitID.VARROCK_DIARY_EASY_COMPLETE),
	VARROCK_MEDIUM("Varrock Medium", AD_TIER.MEDIUM, VarbitID.VARROCK_DIARY_MEDIUM_COMPLETE),
	VARROCK_HARD("Varrock Medium", AD_TIER.HARD, VarbitID.VARROCK_DIARY_HARD_COMPLETE),
	VARROCK_ELITE("Varrock Medium", AD_TIER.ELITE, VarbitID.VARROCK_DIARY_ELITE_COMPLETE),

	WESTERN_PROVINCES_EASY("Western Provinces Easy", AD_TIER.EASY, VarbitID.WESTERN_DIARY_EASY_COMPLETE),
	WESTERN_PROVINCES_MEDIUM("Western Provinces Medium", AD_TIER.MEDIUM, VarbitID.WESTERN_DIARY_MEDIUM_COMPLETE),
	WESTERN_PROVINCES_HARD("Western Provinces Medium", AD_TIER.HARD, VarbitID.WESTERN_DIARY_HARD_COMPLETE),
	WESTERN_PROVINCES_ELITE("Western Provinces Medium", AD_TIER.ELITE, VarbitID.WESTERN_DIARY_ELITE_COMPLETE),

	WILDERNESS_EASY("Wilderness Easy", AD_TIER.EASY, VarbitID.WILDERNESS_DIARY_EASY_COMPLETE),
	WILDERNESS_MEDIUM("Wilderness Medium", AD_TIER.MEDIUM, VarbitID.WILDERNESS_DIARY_MEDIUM_COMPLETE),
	WILDERNESS_HARD("Wilderness Medium", AD_TIER.HARD, VarbitID.WILDERNESS_DIARY_HARD_COMPLETE),
	WILDERNESS_ELITE("Wilderness Medium", AD_TIER.ELITE, VarbitID.WILDERNESS_DIARY_ELITE_COMPLETE);

	private final String name;
	private final AD_TIER tier;
	private final int varbitID;

	public boolean isCompleted(Client client)
	{
		return client.getVarbitValue(varbitID) == IRequirement.COMPLETED;
	}
}