package com.gielinor_sessions.resources.achievement_diaries;

import lombok.AllArgsConstructor;
import lombok.Getter;
import net.runelite.api.gameval.VarbitID;

@Getter
@AllArgsConstructor
public enum AD_GROUP
{
	ARDOUGNE_EASY(
	    AD_REGION.ARDOUGNE,
	    AD_TIER.EASY,
	    VarbitID.ARDOUGNE_DIARY_EASY_COMPLETE),

	ARDOUGNE_MEDIUM(
	    AD_REGION.ARDOUGNE,
	    AD_TIER.MEDIUM,
	    VarbitID.ARDOUGNE_DIARY_MEDIUM_COMPLETE),

	ARDOUGNE_HARD(
	    AD_REGION.ARDOUGNE,
	    AD_TIER.HARD,
	    VarbitID.ARDOUGNE_DIARY_HARD_COMPLETE),

	ARDOUGNE_ELITE(
	    AD_REGION.ARDOUGNE,
	    AD_TIER.ELITE,
	    VarbitID.ARDOUGNE_DIARY_ELITE_COMPLETE),

	DESERT_EASY(
	    AD_REGION.DESERT,
	    AD_TIER.EASY,
	    VarbitID.DESERT_DIARY_EASY_COMPLETE),

	DESERT_MEDIUM(
	    AD_REGION.DESERT,
	    AD_TIER.MEDIUM,
	    VarbitID.DESERT_DIARY_MEDIUM_COMPLETE),

	DESERT_HARD(
	    AD_REGION.DESERT,
	    AD_TIER.HARD,
	    VarbitID.DESERT_DIARY_HARD_COMPLETE),

	DESERT_ELITE(
	    AD_REGION.DESERT,
	    AD_TIER.ELITE,
	    VarbitID.DESERT_DIARY_ELITE_COMPLETE),

	FALADOR_EASY(
	    AD_REGION.FALADOR,
	    AD_TIER.EASY,
	    VarbitID.FALADOR_DIARY_EASY_COMPLETE),

	FALADOR_MEDIUM(
	    AD_REGION.FALADOR,
	    AD_TIER.MEDIUM,
	    VarbitID.FALADOR_DIARY_MEDIUM_COMPLETE),

	FALADOR_HARD(
	    AD_REGION.FALADOR,
	    AD_TIER.HARD,
	    VarbitID.FALADOR_DIARY_HARD_COMPLETE),

	FALADOR_ELITE(
	    AD_REGION.FALADOR,
	    AD_TIER.ELITE,
	    VarbitID.FALADOR_DIARY_ELITE_COMPLETE),

	FREMENNIK_EASY(
	    AD_REGION.FREMENNIK,
	    AD_TIER.EASY,
	    VarbitID.FREMENNIK_DIARY_EASY_COMPLETE),

	FREMENNIK_MEDIUM(
	    AD_REGION.FREMENNIK,
	    AD_TIER.MEDIUM,
	    VarbitID.FREMENNIK_DIARY_MEDIUM_COMPLETE),

	FREMENNIK_HARD(
	    AD_REGION.FREMENNIK,
	    AD_TIER.HARD,
	    VarbitID.FREMENNIK_DIARY_HARD_COMPLETE),

	FREMENNIK_ELITE(
	    AD_REGION.FREMENNIK,
	    AD_TIER.ELITE,
	    VarbitID.FREMENNIK_DIARY_ELITE_COMPLETE),

	KANDARIN_EASY(
	    AD_REGION.KANDARIN,
	    AD_TIER.EASY,
	    VarbitID.KANDARIN_DIARY_EASY_COMPLETE),

	KANDARIN_MEDIUM(
	    AD_REGION.KANDARIN,
	    AD_TIER.MEDIUM,
	    VarbitID.KANDARIN_DIARY_MEDIUM_COMPLETE),

	KANDARIN_HARD(
	    AD_REGION.KANDARIN,
	    AD_TIER.HARD,
	    VarbitID.KANDARIN_DIARY_HARD_COMPLETE),

	KANDARIN_ELITE(
	    AD_REGION.KANDARIN,
	    AD_TIER.ELITE,
	    VarbitID.KANDARIN_DIARY_ELITE_COMPLETE),

	KARAMJA_EASY(
	    AD_REGION.KARAMJA,
	    AD_TIER.EASY,
	    VarbitID.ATJUN_EASY_DONE),

	KARAMJA_MEDIUM(
	    AD_REGION.KARAMJA,
	    AD_TIER.MEDIUM,
	    VarbitID.ATJUN_MED_DONE),

	KARAMJA_HARD(
	    AD_REGION.KARAMJA,
	    AD_TIER.HARD,
	    VarbitID.ATJUN_HARD_DONE),

	KARAMJA_ELITE(
	    AD_REGION.KARAMJA,
	    AD_TIER.ELITE,
	    VarbitID.KARAMJA_DIARY_ELITE_COMPLETE),

	KOUREND_EASY(
	    AD_REGION.KOUREND_KEBOS,
	    AD_TIER.EASY,
	    VarbitID.KOUREND_DIARY_EASY_COMPLETE),

	KOUREND_MEDIUM(
	    AD_REGION.KOUREND_KEBOS,
	    AD_TIER.MEDIUM,
	    VarbitID.KOUREND_DIARY_MEDIUM_COMPLETE),

	KOUREND_HARD(
	    AD_REGION.KOUREND_KEBOS,
	    AD_TIER.HARD,
	    VarbitID.KOUREND_DIARY_HARD_COMPLETE),

	KOUREND_ELITE(
	    AD_REGION.KOUREND_KEBOS,
	    AD_TIER.ELITE,
	    VarbitID.KOUREND_DIARY_ELITE_COMPLETE),

	LUMBRIDGE_EASY(
	    AD_REGION.LUMBRIDGE_DRAYNOR,
	    AD_TIER.EASY,
	    VarbitID.LUMBRIDGE_DIARY_EASY_COMPLETE),

	LUMBRIDGE_MEDIUM(
	    AD_REGION.LUMBRIDGE_DRAYNOR,
	    AD_TIER.MEDIUM,
	    VarbitID.LUMBRIDGE_DIARY_MEDIUM_COMPLETE),

	LUMBRIDGE_HARD(
	    AD_REGION.LUMBRIDGE_DRAYNOR,
	    AD_TIER.HARD,
	    VarbitID.LUMBRIDGE_DIARY_HARD_COMPLETE),

	LUMBRIDGE_ELITE(
	    AD_REGION.LUMBRIDGE_DRAYNOR,
	    AD_TIER.ELITE,
	    VarbitID.LUMBRIDGE_DIARY_ELITE_COMPLETE),

	MORYTANIA_EASY(
	    AD_REGION.MORYTANIA,
	    AD_TIER.EASY,
	    VarbitID.MORYTANIA_DIARY_EASY_COMPLETE),

	MORYTANIA_MEDIUM(
	    AD_REGION.MORYTANIA,
	    AD_TIER.MEDIUM,
	    VarbitID.MORYTANIA_DIARY_MEDIUM_COMPLETE),

	MORYTANIA_HARD(
	    AD_REGION.MORYTANIA,
	    AD_TIER.HARD,
	    VarbitID.MORYTANIA_DIARY_HARD_COMPLETE),

	MORYTANIA_ELITE(
	    AD_REGION.MORYTANIA,
	    AD_TIER.ELITE,
	    VarbitID.MORYTANIA_DIARY_ELITE_COMPLETE),

	VARROCK_EASY(
	    AD_REGION.VARROCK,
	    AD_TIER.EASY,
	    VarbitID.VARROCK_DIARY_EASY_COMPLETE),

	VARROCK_MEDIUM(
	    AD_REGION.VARROCK,
	    AD_TIER.MEDIUM,
	    VarbitID.VARROCK_DIARY_MEDIUM_COMPLETE),

	VARROCK_HARD(
	    AD_REGION.VARROCK,
	    AD_TIER.HARD,
	    VarbitID.VARROCK_DIARY_HARD_COMPLETE),

	VARROCK_ELITE(
	    AD_REGION.VARROCK,
	    AD_TIER.ELITE,
	    VarbitID.VARROCK_DIARY_ELITE_COMPLETE),

	WESTERN_EASY(
	    AD_REGION.WESTERN_PROVINCES,
	    AD_TIER.EASY,
	    VarbitID.WESTERN_DIARY_EASY_COMPLETE),

	WESTERN_MEDIUM(
	    AD_REGION.WESTERN_PROVINCES,
	    AD_TIER.MEDIUM,
	    VarbitID.WESTERN_DIARY_MEDIUM_COMPLETE),

	WESTERN_HARD(
	    AD_REGION.WESTERN_PROVINCES,
	    AD_TIER.HARD,
	    VarbitID.WESTERN_DIARY_HARD_COMPLETE),

	WESTERN_ELITE(
	    AD_REGION.WESTERN_PROVINCES,
	    AD_TIER.ELITE,
	    VarbitID.WESTERN_DIARY_ELITE_COMPLETE),

	WILDERNESS_EASY(
	    AD_REGION.WILDERNESS,
	    AD_TIER.EASY,
	    VarbitID.WILDERNESS_DIARY_EASY_COMPLETE),

	WILDERNESS_MEDIUM(
	    AD_REGION.WILDERNESS,
	    AD_TIER.MEDIUM,
	    VarbitID.WILDERNESS_DIARY_MEDIUM_COMPLETE),

	WILDERNESS_HARD(
	    AD_REGION.WILDERNESS,
	    AD_TIER.HARD,
	    VarbitID.WILDERNESS_DIARY_HARD_COMPLETE),

	WILDERNESS_ELITE(
	    AD_REGION.WILDERNESS,
	    AD_TIER.ELITE,
	    VarbitID.WILDERNESS_DIARY_ELITE_COMPLETE);

	private final AD_REGION region;
	private final AD_TIER tier;
	private final int completionVarbit;

}